export interface ComponentCategory {
  slug: string;
  name: string;
  components: { name: string }[];
}

export const categories: ComponentCategory[] = [
  {
    slug: "accordion",
    name: "Accordion",
    components: [
      { name: "comp-334" },
      { name: "comp-335" },
      { name: "comp-336" },
      { name: "comp-337" },
      { name: "comp-338" },
      { name: "comp-339" },
      { name: "comp-340" },
      { name: "comp-341" },
      { name: "comp-342" },
      { name: "comp-343" },
      { name: "comp-344" },
      { name: "comp-345" },
      { name: "comp-346" },
      { name: "comp-347" },
      { name: "comp-348" },
      { name: "comp-349" },
      { name: "comp-350" },
      { name: "comp-351" },
      { name: "comp-352" },
      { name: "comp-353" },
    ],
  },
  {
    slug: "alert",
    name: "Alert",
    components: [
      { name: "comp-267" },
      { name: "comp-268" },
      { name: "comp-269" },
      { name: "comp-270" },
      { name: "comp-271" },
      { name: "comp-272" },
      { name: "comp-273" },
      { name: "comp-274" },
      { name: "comp-275" },
      { name: "comp-276" },
      { name: "comp-277" },
      { name: "comp-278" },
    ],
  },
  {
    slug: "avatar",
    name: "Avatar",
    components: [
      { name: "comp-390" },
      { name: "comp-391" },
      { name: "comp-392" },
      { name: "comp-393" },
      { name: "comp-394" },
      { name: "comp-395" },
      { name: "comp-396" },
      { name: "comp-397" },
      { name: "comp-398" },
      { name: "comp-399" },
      { name: "comp-400" },
      { name: "comp-401" },
      { name: "comp-402" },
      { name: "comp-403" },
      { name: "comp-404" },
      { name: "comp-405" },
      { name: "comp-406" },
      { name: "comp-407" },
      { name: "comp-408" },
      { name: "comp-409" },
      { name: "comp-410" },
      { name: "comp-411" },
      { name: "comp-412" },
    ],
  },
  {
    slug: "badge",
    name: "Badge",
    components: [
      { name: "comp-413" },
      { name: "comp-414" },
      { name: "comp-415" },
      { name: "comp-416" },
      { name: "comp-417" },
      { name: "comp-418" },
      { name: "comp-419" },
      { name: "comp-420" },
      { name: "comp-421" },
      { name: "comp-422" },
      { name: "comp-423" },
      { name: "comp-424" },
      { name: "comp-425" },
    ],
  },
  {
    slug: "banner",
    name: "Banner",
    components: [
      { name: "comp-301" },
      { name: "comp-302" },
      { name: "comp-303" },
      { name: "comp-304" },
      { name: "comp-305" },
      { name: "comp-306" },
      { name: "comp-307" },
      { name: "comp-308" },
      { name: "comp-309" },
      { name: "comp-310" },
      { name: "comp-311" },
      { name: "comp-312" },
    ],
  },
  {
    slug: "breadcrumb",
    name: "Breadcrumb",
    components: [
      { name: "comp-446" },
      { name: "comp-447" },
      { name: "comp-448" },
      { name: "comp-449" },
      { name: "comp-450" },
      { name: "comp-451" },
      { name: "comp-452" },
      { name: "comp-453" },
    ],
  },
  {
    slug: "button",
    name: "Button",
    components: [
      { name: "comp-78" },
      { name: "comp-79" },
      { name: "comp-80" },
      { name: "comp-81" },
      { name: "comp-82" },
      { name: "comp-83" },
      { name: "comp-84" },
      { name: "comp-85" },
      { name: "comp-86" },
      { name: "comp-87" },
      { name: "comp-88" },
      { name: "comp-89" },
      { name: "comp-90" },
      { name: "comp-91" },
      { name: "comp-92" },
      { name: "comp-93" },
      { name: "comp-94" },
      { name: "comp-95" },
      { name: "comp-96" },
      { name: "comp-97" },
      { name: "comp-98" },
      { name: "comp-99" },
      { name: "comp-100" },
      { name: "comp-101" },
      { name: "comp-129" },
      { name: "comp-130" },
      { name: "comp-102" },
      { name: "comp-103" },
      { name: "comp-104" },
      { name: "comp-105" },
      { name: "comp-106" },
      { name: "comp-107" },
      { name: "comp-108" },
      { name: "comp-109" },
      { name: "comp-110" },
      { name: "comp-111" },
      { name: "comp-112" },
      { name: "comp-113" },
      { name: "comp-114" },
      { name: "comp-131" },
      { name: "comp-115" },
      { name: "comp-116" },
      { name: "comp-117" },
      { name: "comp-118" },
      { name: "comp-119" },
      { name: "comp-120" },
      { name: "comp-121" },
      { name: "comp-122" },
      { name: "comp-123" },
      { name: "comp-124" },
      { name: "comp-125" },
      { name: "comp-126" },
      { name: "comp-127" },
      { name: "comp-128" },
    ],
  },
  {
    slug: "calendar-date-picker",
    name: "Calendar & Date picker",
    components: [
      { name: "comp-487" },
      { name: "comp-488" },
      { name: "comp-489" },
      { name: "comp-490" },
      { name: "comp-491" },
      { name: "comp-492" },
      { name: "comp-493" },
      { name: "comp-494" },
      { name: "comp-495" },
      { name: "comp-496" },
      { name: "comp-497" },
      { name: "comp-498" },
      { name: "comp-499" },
      { name: "comp-500" },
      { name: "comp-501" },
      { name: "comp-502" },
      { name: "comp-503" },
      { name: "comp-504" },
      { name: "comp-505" },
      { name: "comp-506" },
      { name: "comp-507" },
      { name: "comp-508" },
      { name: "comp-509" },
      { name: "comp-510" },
      { name: "comp-41" },
      { name: "comp-42" },
      { name: "comp-511" },
      { name: "comp-512" },
    ],
  },
  {
    slug: "checkbox",
    name: "Checkbox",
    components: [
      { name: "comp-132" },
      { name: "comp-133" },
      { name: "comp-134" },
      { name: "comp-135" },
      { name: "comp-136" },
      { name: "comp-137" },
      { name: "comp-138" },
      { name: "comp-139" },
      { name: "comp-151" },
      { name: "comp-140" },
      { name: "comp-141" },
      { name: "comp-142" },
      { name: "comp-143" },
      { name: "comp-144" },
      { name: "comp-145" },
      { name: "comp-146" },
      { name: "comp-147" },
      { name: "comp-148" },
      { name: "comp-149" },
      { name: "comp-150" },
    ],
  }, 
  {
    slug: "textarea",
    name: "Textarea",
    components: [
      { name: "comp-59" },
      { name: "comp-60" },
      { name: "comp-61" },
      { name: "comp-62" },
      { name: "comp-63" },
      { name: "comp-64" },
      { name: "comp-65" },
      { name: "comp-66" },
      { name: "comp-67" },
      { name: "comp-68" },
      { name: "comp-69" },
      { name: "comp-70" },
      { name: "comp-71" },
      { name: "comp-72" },
      { name: "comp-73" },
      { name: "comp-74" },
      { name: "comp-75" },
      { name: "comp-76" },
      { name: "comp-77" },
    ],
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    components: [
      { name: "comp-354" },
      { name: "comp-355" },
      { name: "comp-356" },
      { name: "comp-357" },
      { name: "comp-358" },
      { name: "comp-359" },
      { name: "comp-360" },
      { name: "comp-361" },
      { name: "comp-362" },
      { name: "comp-363" },
      { name: "comp-364" },
      { name: "comp-365" },
    ],
  },
  {
    slug: "view",
    name: "View All",
    components: [
      { name: "comp-390" },
      { name: "comp-391" },
      { name: "comp-392" },
      { name: "comp-393" },
    ],
  },
];

export function getCategory(slug: string): ComponentCategory | undefined {
  return categories.find((category) => category.slug === slug);
}