import { BoxProps } from "@/components/_components/box";

const mainSlug = "docs/components";

export const components: BoxProps[] = [
  {
    image: "accordion",
    name: "Accordion",
    slug: `${mainSlug}/accordion`,
    isComing: true,
    components: [],
  },
  {
    image: "alert",
    name: "Alert",
    slug: `${mainSlug}/alert`,
    componentsType: "components",
    components: [
      { name: "alert-01" },
      { name: "alert-02" },
      { name: "alert-03" },
      { name: "alert-04" },
      { name: "alert-05" },
      { name: "alert-06" },
      { name: "alert-07" },
      { name: "alert-08" },
      { name: "alert-09" },
      { name: "alert-10" },
    ],
  },
  {
    image: "avatar",
    name: "Avatar",
    slug: `${mainSlug}/avatar`,
    isComing: true,
    components: [],
  },

  {
    image: "button",
    name: "Button",
    slug: `${mainSlug}/button`,
    componentsType: "components",
    components: [
      { name: "button-01" },
      { name: "button-02" },
      { name: "button-03" },
      { name: "button-04" },
      { name: "button-05" },
      { name: "button-06" },
      { name: "button-07" },
      { name: "button-08" },
      { name: "button-09" },
      { name: "button-10" },
      { name: "button-11" },
      { name: "button-12" },
      { name: "button-13" },
      { name: "button-14" },
      { name: "button-15" },
      { name: "button-16" },
      { name: "button-17" },
      { name: "button-18" },
      { name: "button-19" },
      { name: "button-20" },
      { name: "button-21" },
      { name: "button-22" },
      { name: "button-23" },
      { name: "button-24" },
      { name: "button-25" },
      { name: "button-26" },
      { name: "button-27" },
      { name: "button-28" },
      { name: "button-29" },
      { name: "button-30" },
      { name: "button-31" },
      { name: "button-32" },
      { name: "button-33" },
      { name: "button-34" },
      { name: "button-35" },
      { name: "button-36" },
      { name: "button-37" },
      { name: "button-38" },
      { name: "button-39" },
      { name: "button-40" },
      { name: "button-41" },
      { name: "button-42" },
      { name: "button-43" },
      { name: "button-44" },
      { name: "button-45" },
      { name: "button-46" },
      { name: "button-47" },
      { name: "button-48" },
      { name: "button-49" },
      { name: "button-50" },
      { name: "button-51" },
    ],
  },
  {
    image: "checkbox",
    name: "Checkbox",
    slug: `${mainSlug}/checkbox`,
    componentsType: "components",
    components: [
      { name: "checkbox-01" },
      { name: "checkbox-02" },
      { name: "checkbox-03" },
      { name: "checkbox-04" },
      { name: "checkbox-05" },
      { name: "checkbox-06" },
      { name: "checkbox-07" },
      { name: "checkbox-08" },
      { name: "checkbox-09" },
      { name: "checkbox-10" },
      { name: "checkbox-11" },
      { name: "checkbox-12" },
      { name: "checkbox-13" },
      { name: "checkbox-14" },
      { name: "checkbox-15" },
      { name: "checkbox-16" },
      { name: "checkbox-17" },
    ],
  },

  {
    image: "preview",
    name: "Heading",
    slug: `${mainSlug}/heading`,
    componentsType: "typography",
    components: [
      { name: "heading-01" },
      { name: "heading-02" },
      { name: "heading-03" },
      { name: "heading-04" },
      { name: "heading-05" },
      { name: "heading-06" },
    ],
  },
  {
    image: "preview",
    name: "Description",
    slug: `${mainSlug}/description`,
    componentsType: "typography",
    components: [
      { name: "description-01" },
      { name: "description-02" },
      { name: "description-03" },
    ],
  },

  {
    image: "textarea",
    name: "Textarea",
    slug: `${mainSlug}/textarea`,
    componentsType: "components",
    components: [
      { name: "textarea-01" },
      { name: "textarea-02" },
      { name: "textarea-03" },
      { name: "textarea-04" },
      { name: "textarea-05" },
      { name: "textarea-06" },
      { name: "textarea-07" },
      { name: "textarea-08" },
      { name: "textarea-09" },
      { name: "textarea-10" },
      { name: "textarea-11" },
      { name: "textarea-12" },
      { name: "textarea-13" },
      { name: "textarea-14" },
      { name: "textarea-15" },
      { name: "textarea-16" },
      { name: "textarea-17" },
      { name: "textarea-18" },
      { name: "textarea-19" },
    ],
  },
  {
    image: "slider",
    name: "Slider",
    slug: `${mainSlug}/slider`,
    componentsType: "components",
    components: [
      { name: "slider-01" },
      { name: "slider-02" },
      { name: "slider-03" },
      { name: "slider-04" },
      { name: "slider-05" },
      { name: "slider-06" },
      { name: "slider-07" },
      { name: "slider-08" },
      { name: "slider-09" },
      { name: "slider-10" },
      { name: "slider-11" },
      { name: "slider-12" },
      { name: "slider-13" },
      { name: "slider-14" },
      { name: "slider-15" },
      { name: "slider-16" },
      { name: "slider-17" },
      { name: "slider-18" },
      { name: "slider-19" },
      { name: "slider-20" },
      { name: "slider-21" },
      { name: "slider-22" },
      { name: "slider-23" },
    ],
  },
  {
    image: "select",
    name: "Select",
    slug: `${mainSlug}/select`,
    componentsType: "components",
    components: [
      { name: "select-01" },
      { name: "select-02" },
      { name: "select-03" },
      { name: "select-04" },
      { name: "select-05" },
      { name: "select-06" },
      { name: "select-07" },
      { name: "select-08" },
      { name: "select-09" },
      { name: "select-10" },
      { name: "select-11" },
      { name: "select-12" },
      { name: "select-13" },
    ],
  },
  {
    image: "switch",
    name: "Switch",
    slug: `${mainSlug}/switch`,
    componentsType: "components",
    components: [
      { name: "switch-01" },
      { name: "switch-02" },
      { name: "switch-03" },
      { name: "switch-04" },
      { name: "switch-05" },
      { name: "switch-06" },
      { name: "switch-07" },
      { name: "switch-08" },
      { name: "switch-09" },
      { name: "switch-10" },
      { name: "switch-11" },
      { name: "switch-12" },
      { name: "switch-13" },
      { name: "switch-14" },
      { name: "switch-15" },
      { name: "switch-16" },
      { name: "switch-17" },
    ],
  },

  {
    image: "view",
    slug: `${mainSlug}`,
    name: "View All",
    componentsType: "components",
    components: [
      { name: "alerts" },
      { name: "badges" },
      { name: "banners" },
      { name: "breadcrumbs" },
      { name: "buttons" },
      { name: "checkboxs" },
      { name: "descriptions" },
      { name: "headings" },
      { name: "notifications" },
      { name: "radios" },
      { name: "selects" },
      { name: "sliders" },
      { name: "switchs" },
      { name: "textareas" },
    ],
  },
];

export function getComponent(slug: string): BoxProps | undefined {
  return components.find((component) => component.slug === slug);
}
